# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rj7UeubgwLKUo8CkL3yXSO9BSNcEmioE
"""

import streamlit as st
import random

st.title('Test Streamlit!')
st.write('Hello World!')

if st.button('Genearate Random Number'):
  random_number = random.randint(1, 100)
  st.write(f'Random Numbera: {random_number}')